steps:
  # Instalar dependências
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['ci']

  # Build da aplicação
  - name: 'node:18'
    entrypoint: 'npm'
    args: ['run', 'build']

  # Build da imagem Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:$BUILD_ID',
      '-t', 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:latest',
      '.'
    ]

  # Push da imagem para Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:$BUILD_ID']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:latest']

  # Deploy no Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'whatsapp-rag-dashboard',
      '--image', 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:$BUILD_ID',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '8080',
      '--memory', '512Mi',
      '--cpu', '1',
      '--max-instances', '10',
      '--min-instances', '1'
    ]

# Configuração de timeout e opções
timeout: '1200s'
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_MEDIUM'

# Artefatos a serem salvos
artifacts:
  images:
    - 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:$BUILD_ID'
    - 'gcr.io/$PROJECT_ID/whatsapp-rag-dashboard:latest'